destDir = "/"
sourceDir = ".local/share/chezmoi/root"

[genericSecret]
command = "lpass"

[data.vars.donata]
root_param = "/dev/mapper/cryptroot cryptdevice=UUID=:cryptroot"

[data.vars.marea]
root_param = "/dev/mapper/cryptroot cryptdevice=UUID=6062fcc2-4462-422a-9dea-33dd5b789863:cryptroot"

[data.vars.fortuna]
root_param = "PARTUUID=6d216b40-32a7-4b60-b53d-5386b7ad028f"
