destDir = "."
sourceDir = ".local/share/chezmoi/home"

[merge]
command = "nvim"
args = ["-d", "-u", "NONE"]

[diff]
exclude = ["scripts"]

[data.vars.donata]
network = "wlp58s0"
touchpad = "1739:30383:DLL075B:01_06CB:76AF_Touchpad"
keyboard = "1:1:AT_Translated_Set_2_keyboard"
screen = [
  "output eDP-1 resolution 3200x1800@60Hz position 840,2160 scale 1.6",
  "output DP-1 resolution 3840x2160@59.997002Hz position 0,0 scale 1",

]
laptop = true
dpi = "166.0"
git_signingkey = "E735DF276C508071"
editor = "helix"

[data.vars.fortuna]
network = "enp7s0"
touchpad = "1267:12454:ELAN0406:00_04F3:30A6_Touchpad"
keyboard = "1:1:AT_Translated_Set_2_keyboard"
screen = [
  "output HDMI-A-1 resolution 2560x1440@119.998001Hz position 1080,0 scale 1.0",
  "output DVI-I-1 resolution 1920x1080@60Hz position 0,0 scale 1.0 transform 270",
  "output DP-1 disable",
]
laptop = false
git_signingkey = "E735DF276C508071"

[data.vars.carla]
terminal_font_size = "13.0"
pinentry = "/opt/homebrew/bin/pinentry-curses"
shell = "fish"
decorations = "none"
git_signingkey = "CBA412CC"
