destDir = "/"
sourceDir = ".local/share/chezmoi/root"

[genericSecret]
command = "lpass"

[data.vars.donata]
root_param = "/dev/mapper/cryptroot cryptdevice=UUID=b224f0fb-acd4-4872-8c97-72b13d748510:cryptroot"

[data.vars.marea]
root_param = "/dev/mapper/cryptroot cryptdevice=UUID=a5be4c00-e4a8-4681-b766-5eb1112180fa:cryptroot"

[data.vars.fortuna]
root_param = "PARTUUID=6d216b40-32a7-4b60-b53d-5386b7ad028f"
