destDir = "/home/martynas"
sourceDir = ".local/share/chezmoi/home"

[genericSecret]
command = "lpass"

[merge]
  command = "nvim"
  args = ["-d", "-u", "NONE"]

[data.vars.donata]
wireless = "wlp58s0"
touchpad = "1739:30383:DLL075B:01_06CB:76AF_Touchpad"
keyboard = "1:1:AT_Translated_Set_2_keyboard"
screen = "3200x1800@60Hz position 600,1800 scale 1.6"
scale_factor = "2"

[data.vars.marea]
wireless = "wlp2s0"
touchpad = "1267:12454:ELAN0406:00_04F3:30A6_Touchpad"
keyboard = "5426:581:Razer_Razer_Blade_Keyboard"
screen = "1920x1080@240Hz position 0,0 scale 1.0"
scale_factor = "1"

[data.vars.fortuna]
wireless = "enp6s0"
touchpad = "1267:12454:ELAN0406:00_04F3:30A6_Touchpad"
keyboard = "1:1:AT_Translated_Set_2_keyboard"
screen = [
  "output DP-1 resolution 2560x1440@143.856003Hz position 1080,0 scale 1.0",
  "output DP-2 resolution 1920x1080@60Hz position 0,0 scale 1.0 transform 270"
]
scale_factor = "1"
