#!/bin/sh
# Xsetup - run as root before the login dialog appears

# Radeon VII setup
#xrandr --output DisplayPort-0 --mode 2560x1440 --rate 144 --primary
#xrandr --output DisplayPort-1 --off
#xrandr --output HDMI-A-0 --off

# 2080 Super with Nvidia drivers setup
xrandr --output DP-2 --mode 2560x1440 --rate 144 --primary \
       --output DP-1 --off \
       --output DP-0 --off
