addSbtPlugin("net.virtual-void"    % "sbt-dependency-graph" % "0.9.1")
addSbtPlugin("com.github.tkawachi" % "sbt-repeat"           % "0.1.0")
addSbtPlugin("io.spray"            % "sbt-revolver"         % "0.9.1")
addSbtPlugin("com.timushev.sbt"    % "sbt-updates"          % "0.6.3")
addSbtPlugin("com.github.tkawachi" % "sbt-repeat"           % "0.1.0")
