addSbtPlugin("net.virtual-void"    % "sbt-dependency-graph" % "0.9.1")
addSbtPlugin("com.jsuereth"        % "sbt-pgp"              % "1.1.0")
addSbtPlugin("com.github.tkawachi" % "sbt-repeat"           % "0.1.0")
addSbtPlugin("io.spray"            % "sbt-revolver"         % "0.9.1")
addSbtPlugin("com.timushev.sbt"    % "sbt-updates"          % "0.3.4")
addSbtPlugin("com.github.tkawachi" % "sbt-repeat"           % "0.1.0")
addSbtPlugin("ch.epfl.scala"       % "sbt-bloop"            % "1.3.4")
