addSbtPlugin("net.virtual-void"    % "sbt-dependency-graph" % "0.8.2")
addSbtPlugin("com.jsuereth"        % "sbt-pgp"              % "1.0.1")
addSbtPlugin("io.get-coursier"     % "sbt-coursier"         % "1.0.0-RC6")
addSbtPlugin("com.github.tkawachi" % "sbt-repeat"           % "0.0.1")
addSbtPlugin("io.spray"            % "sbt-revolver"         % "0.8.0")
